### ISSUE TITLE
Installation issues on Windows 11

### ISSUE THREAD

**Issue by cakrit** [netdata/msi-installer#19]
I already have a WSL2 with custom install of netdata running on my Windows 11.

I ran the latest installer. It rebooted the machine, though it shouldn't have, since I already had WSL2 here. 

After the reboot, there was no Netdata. I ran again the msi, still nothing. No wsl installation with the netdata deployment, no error message that I could see, just silent failure. In the "Add or remove programs" I see NetdataWSL, so I'll uninstall and wait for fixes.

**Comment by dfpr** [comment]
I'll set it to restart only when necessary and will put the installation logs soon.

**Comment by dfpr** [comment]
Reboot was prematurely unregistering the installation, please try 5434150c751b7d824e88ee6f914160d26f134673 that also adds an installation log at c:\netdata.log. Not forcing a reboot unnecessarily still pending fix.

**Comment by cakrit** [comment]
Still doesn't work with the latest release. On the last run, it did reboot my machine, but nothing happened after the installation. 
I even ran it a second time after the restart, just in case, but nothing. Attaching the log. 
[netdata.log](https://github.com/netdata/msi-installer/files/9953555/netdata.log)

**Comment by dfpr** [comment]
It is a requirement to run the MSI from a privileged context, for example from an admin terminal with the `msiexec /i netdata.msi`. The reason for this is that after the reboot the installation can only continue for the user that initiated it since WSL is not available for the System user that regular Windows Services use.

**Comment by cakrit** [comment]
I ran it via msiexec from a normal cmd, same issue. Now I'll try again after running cmd as an Administrator and see. It's very unfriendly to users, but I understand, let's hope it will work this time.

**Comment by cakrit** [comment]
It worked very well when executed from an admin cmd. 
Normal users can't even see the wsl distro, need an admin command to see `wsl -l -v` return the distro. It works though!

**Comment by dfpr** [comment]
> I ran it via msiexec from a normal cmd, same issue. Now I'll try again after running cmd as an Administrator and see. It's very unfriendly to users, but I understand, let's hope it will work this time.

Readme does mention the admin cmd requirement, one way to overcome this would be using a MSI bootstrapper which is basically an EXE file can include the MSI and run `msiexec` with admin privileges. Notice that, since WSL can't work without a user logged in, using a MSI for unattended remote installations that usually use the SYSTEM windows user will fail unless the installation command is run from a logged in user.

**Comment by dfpr** [comment]
> It worked very well when executed from an admin cmd. Normal users can't even see the wsl distro, need an admin command to see `wsl -l -v` return the distro. It works though!

That shouldn't happen, WSL should be usable to the user who installed the distro, unless the actual Administrator user was used during installation but this issue would apply to any other software.

**Comment by cakrit** [comment]
You're right, now I see it as a normal user too. Perhaps I ran it too fast after the restart as a normal user and it didn't show up.
