### ISSUE TITLE
Option to not restart immediately

### ISSUE THREAD

**Issue by cakrit** [netdata/msi-installer#24]
Provide a way to postpone the restart, for a user to select the most appropriate time to do it. Perhaps a mandatory option off RESTART=NOW or RESTART=LATER or whatever is commonly done for such cases.

**Comment by Ferroin** [comment]
The normal approach here is to flag the system as needing a restart. I’m not 100% certain _how_ this is typically done, but when done right the user gets notified that the system needs restarted to finish installing things, and can then choose to do so at their leisure.

**Comment by dfpr** [comment]
I didn't put a notification for restarting so it is as automated as possible.

**Comment by Ferroin** [comment]
The current approach is unusable with tools like Ansible or Puppet though, because they expect that the system will not randomly reboot while they’re executing things on it unless they explicitly told it to reboot.

I do think there’s value in having a way to explicitly ask it to just reboot, but the default expectation among most users is that the system does not get arbitrarily rebooted without user intervention.

**Comment by cakrit** [comment]
We won't be suggesting this for production use @Ferroin, there's some new info I'll send you.

**Comment by cakrit** [comment]
Let's not do this, since it will not be used for production systems. We have warnings.

**Comment by cakrit** [comment]
I mean we have warnings in the documentation.
