### ISSUE TITLE
When using, only the traffic of the WSL network card is detected, but the traffic of the network card that my system is really using is not detected

### ISSUE THREAD

**Issue by KNaiFen** [netdata/msi-installer#29]
When using, only the traffic of the WSL network card is detected, but the traffic of the network card that my system is really using is not detected
When using Docker on Win2022, it is the same as the current situation. Only the traffic generated by the WSL network card can be monitored. 
Is there any solution?Let me monitor the real network card traffic
In addition, I noticed that the window was refreshed quickly during installation. I noticed that the red ink was reported, but the window did not give me any time to respond. After the fast refresh, the window closed itself, causing me to see no error messages

**Comment by cakrit** [comment]
The installation is messed up now, and you see irrelevant things. See if you have the same as shown below. If you do, move `netdata.conf?` to `netdata.conf` and run restart-netdata on a cmd shell.

@dfpr see below, something is broken now.
<img width="658" alt="image" src="https://user-images.githubusercontent.com/43294513/203082895-065a36c3-d569-404a-9631-5f444de3329f.png">

**Comment by cakrit** [comment]
@KNaiFen your data should still appear as seen below, but we know how confusing all the other charts are, which is why netdata.conf should have been customized to disable those collectors by default.

<img width="872" alt="image" src="https://user-images.githubusercontent.com/43294513/203084190-d82701a2-3ef6-44f1-92ec-9af9c9eb9908.png">

**Comment by KNaiFen** [comment]
I'm sorry that my ”restart-netdata“ doesn't work. I forgot to explain this before. I'm sorry
![3](https://user-images.githubusercontent.com/53338804/203094779-758d8195-f5db-4476-8d49-375ea5f660d7.jpg)

**Comment by dfpr** [comment]
@KNaiFen you can find the installation log at c:\netdata.log, latest commit also removes red text from installation script and adds more logging to the path adjustment, try it please since I have not been able to reproduce your 'restart-netdata' script issue.

@cakrit netdata.conf issue was caused by incorrect script encoding, it should work correctly now with the latest commit

**Comment by cakrit** [comment]
@dfpr sorry but I still see the exact same result. I even triggered the build again, in case it wasn't done after the commit you mentioned.

**Comment by dfpr** [comment]
> @dfpr sorry but I still see the exact same result. I even triggered the build again, in case it wasn't done after the commit you mentioned.

fixed, build action was checking out using Windows line endings for linux scripts
btw, commits don't automatically trigger the Build action currently

**Comment by cakrit** [comment]
Yes, @Ferroin will automate that eventually, but for now we need to trigger builds manually.

**Comment by cakrit** [comment]
The proper default config is back in and works fine.
